apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-backend-deployment
spec:
  selector:
    matchLabels:
      app: react-app-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: react-app-backend
    spec:
      containers:
        - name: react-app-backend
          image: react-app-backend:v1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"